source 'https://rubygems.org'

ruby '>= 3.0.0'

gem 'sinatra', '~> 3.2'
gem 'sinatra-contrib', '~> 3.2'
gem 'puma', '~> 6.4'
gem 'sequel', '~> 5.78'
gem 'pg', '~> 1.5'
gem 'dotenv', '~> 3.1'
gem 'httparty', '~> 0.22'
gem 'smallpict'
gem 'securerandom'
